version: "3"
services:
  database-mysql:
    platform: linux/amd64
    container_name: mysql-mss
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: 'simple'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'mss'
      TZ: Asia/Seoul

    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

    ports:
      - '13306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
