
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/mss
    username: simple
    password: simple

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


mss:
  point:
    max-attendance: 10